include: package:flutter_lints/flutter.yaml

linter:
  rules:
    prefer_single_quotes: true

analyzer:
  exclude:
    # for retrofit and json_serializable
    - "**/*.g.dart"
    # for freezed
    - "**/*.freezed.dart"

  errors:
    invalid_annotation_target: ignore
    unused_element: ignore
    depend_on_referenced_packages: ignore
    use_build_context_synchronously: ignore
    require_trailing_commas: true
    deprecated_member_use: ignore

  plugins:
    - custom_lint
